DROP TABLE VOL;
DROP TABLE TERMINAL;
DROP TABLE AEROPORT;
DROP TABLE COMPAGNIE;

CREATE TABLE COMPAGNIE(
    codeC NUMBER PRIMARY KEY,
    nomC VARCHAR2(100),
    siegesocialC VARCHAR2(100)
);

CREATE TABLE AEROPORT(
    nomA VARCHAR2(100) PRIMARY KEY,
    paysA VARCHAR2(100),
    villeA VARCHAR2(100)
);

CREATE TABLE TERMINAL(
    idTerminal VARCHAR2(9) PRIMARY KEY,
    nomA VARCHAR2(100),
    FOREIGN KEY (nomA) REFERENCES AEROPORT(nomA)
);

CREATE TABLE VOL(
    numVol NUMBER,
    dateheureDEP DATE,
    dateheureARR DATE,
    codeC NUMBER,
    AeroportDEP VARCHAR2(100),
    AeroportARR VARCHAR2(100),
    terminalDEP VARCHAR2(9),
    terminalARR VARCHAR2(9),
    PRIMARY KEY (numVol, dateheureDEP, codeC),
    FOREIGN KEY (CodeC) REFERENCES COMPAGNIE(CodeC),
    FOREIGN KEY (AeroportDEP) REFERENCES AEROPORT(nomA),
    FOREIGN KEY (AeroportARR) REFERENCES AEROPORT(nomA),
    FOREIGN KEY (terminalDEP) REFERENCES TERMINAL(idTerminal),
    FOREIGN KEY (terminalARR) REFERENCES TERMINAL(idTerminal)
);
