DROP TABLE VOL PURGE;
DROP TABLE TERMINAL PURGE;
DROP TABLE AEROPORT PURGE;
DROP TABLE COMPAGNIE PURGE;

CREATE TABLE COMPAGNIE(
    codeC NUMBER PRIMARY KEY,
    nomC VARCHAR2(100),
    siegesocialC VARCHAR2(100)
);

CREATE TABLE AEROPORT(
    nomA VARCHAR2(100) PRIMARY KEY,
    paysA VARCHAR2(100),
    villeA VARCHAR2(100)
);

CREATE TABLE TERMINAL(
    idTerminal VARCHAR2(9) PRIMARY KEY,
    nomA VARCHAR2(100),
    FOREIGN KEY (nomA) REFERENCES AEROPORT(nomA)
);

CREATE TABLE VOL(
    numVol NUMBER,
    dateheureDEP DATE,
    dateheureARR DATE,
    codeC NUMBER,
    AeroportDEP VARCHAR2(100),
    AeroportARR VARCHAR2(100),
    terminalDEP VARCHAR2(9),
    terminalARR VARCHAR2(9),
    CONSTRAINT vol_pk PRIMARY KEY (numVol, dateheureDEP, codeC),
    CONSTRAINT vol_fk_codec FOREIGN KEY (CodeC) REFERENCES COMPAGNIE(CodeC),
    CONSTRAINT vol_fk_aeroportdep FOREIGN KEY (AeroportDEP) REFERENCES AEROPORT(nomA),
    CONSTRAINT vol_fk_aeroportarr FOREIGN KEY (AeroportARR) REFERENCES AEROPORT(nomA),
    CONSTRAINT vol_fk_terminaldep FOREIGN KEY (terminalDEP) REFERENCES TERMINAL(idTerminal),
    CONSTRAINT vol_fk_terminalarr FOREIGN KEY (terminalARR) REFERENCES TERMINAL(idTerminal)
);

